adding pendaftaran for pengurus/komunitas
jatimdevday/backend_jdd pull request #21
Opened 2020-10-24 17:26 UTC by kuuhaku86

Menambahkan app register dengan model Community (Komunitas) dan Manager (Pengurus). Dimana model dari masing-masing :
Community :
- name
- city
- description
- logo
- telegram

Manager :
- name
- email
- picture
- community (FK refer to Community)

And you can see the basic form at route
/register/community (for Community)
/register/manager (for Manager)

I'm also adding these Model into django admin page so we can see the data that inserted to the system

resolve #11

2020-10-24 17:28 UTC, kuuhaku86 commented
I think something that make the CI check failed is something that have relation with the .env, firstly I'm got that error after trying to run the app. But after cp .env.example .env I can run this app successfully.

2020-10-25 02:59 UTC, tegarimansyah requested changes

2020-10-25 02:59 UTC, tegarimansyah commented on jdd_community_backend/jdd_community_backend/urls.py
> +from register.views import CommunityCreate, ManagerCreate
Mending mana kalo kata katanya jadi CreateCommunityView dan CreateManagerView ?

2020-10-25 02:59 UTC, tegarimansyah commented on jdd_community_backend/register/forms.py
> +from register.models import Community, Manager
modul buatan sendiri harusnya ditulis dibawah modul yang terinstall. Jadi:

```python
from django.forms import ModelForm, ModelChoiceField
from register.models import Community, Manager
```

2020-10-25 03:01 UTC, kuuhaku86 commented on jdd_community_backend/jdd_community_backend/urls.py
> +from register.views import CommunityCreate, ManagerCreate
Oiya ya, mending gitu sepertinya

2020-10-25 03:02 UTC, tegarimansyah commented
btw, kemarin manager yang kamu tulis disana sebenarnya adalah django User yang memiliki akses ke community. Jadi mungkin manager bisa diganti menjadi extend dari User

2020-10-25 03:03 UTC, kuuhaku86 commented on jdd_community_backend/register/forms.py
> +from register.models import Community, Manager
Hoo oke2 mas

2020-10-25 03:04 UTC, kuuhaku86 commented
> btw, kemarin manager yang kamu tulis disana sebenarnya adalah django User yang memiliki akses ke community. Jadi mungkin manager bisa diganti menjadi extend dari User

Oke mas, saya sesuaikan dahulu

2020-10-25 09:42 UTC, merged